In [1]:
import pandas as pd
import geopandas as gpd
from shapely.geometry import Point
import matplotlib.pyplot as plt

In [2]:
df_uhi = gpd.read_parquet("../output/uhi_data_processed.parquet")
gdf_buildings = gpd.read_parquet("../output/building_data_processed.parquet")
gdf_ndvi = gpd.read_parquet("../output/sentinel2.parquet")
gdf_lst = gpd.read_parquet("../output/landsat_lst.parquet")
df_weather = pd.read_parquet("../output/weather_data_processed.parquet")

In [3]:
# df_uhi
df_uhi.info()
df_uhi.head()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 11229 entries, 0 to 11228
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Longitude  11229 non-null  float64
 1   Latitude   11229 non-null  float64
 2   datetime   11229 non-null  datetime64[ns]
 3   UHI Index  11229 non-null  float64
 4   geometry   11229 non-null  geometry
dtypes: datetime64[ns](1), float64(3), geometry(1)
memory usage: 438.8 KB

,Longitude,Latitude,datetime,UHI Index,geometry
0,-73.909167,40.813107,2021-07-24 15:53:00,1.030289,POINT (1009393.606 235526.824)
1,-73.909187,40.813045,2021-07-24 15:53:00,1.030289,POINT (1009388.093 235504.35)
2,-73.909215,40.812978,2021-07-24 15:53:00,1.023798,POINT (1009380.276 235480.052)
3,-73.909242,40.812908,2021-07-24 15:53:00,1.023798,POINT (1009372.92 235454.541)
4,-73.909257,40.812845,2021-07-24 15:53:00,1.021634,POINT (1009368.791 235431.463)

In [4]:
gdf_buildings.info()
gdf_buildings.head()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 1082896 entries, 0 to 1082895
Data columns (total 5 columns):
 #   Column               Non-Null Count    Dtype
---  ------               --------------    -----
 0   shape_area           1082896 non-null  float64
 1   heightroof           1082896 non-null  float64
 2   groundelev           1082896 non-null  float64
 3   geometry             1082896 non-null  geometry
 4   calculated_area_sqm  1082896 non-null  float64
dtypes: float64(4), geometry(1)
memory usage: 41.3 MB

,shape_area,heightroof,groundelev,geometry,calculated_area_sqm
0,0.0,29.749853,40.0,"MULTIPOLYGON (((993508.772 167345.645, 993452....",152.188049
1,0.0,22.630000,39.0,"MULTIPOLYGON (((937651.67 172257.299, 937650.8...",70.012084
2,0.0,35.760000,51.0,"MULTIPOLYGON (((930033.534 141941.58, 930007.8...",66.792573
3,0.0,37.500000,6.0,"MULTIPOLYGON (((995046.423 149655.549, 995041....",108.479500
4,0.0,18.015113,93.0,"MULTIPOLYGON (((1052344.058 214771.63, 1052356...",163.017750

In [5]:
gdf_ndvi.info()
gdf_ndvi.head()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 19708920 entries, 0 to 19708919
Data columns (total 6 columns):
 #   Column       Dtype
---  ------       -----
 0   y            float64
 1   x            float64
 2   spatial_ref  int32
 3   time         datetime64[ns]
 4   NDVI         float64
 5   geometry     geometry
dtypes: datetime64[ns](1), float64(3), geometry(1), int32(1)
memory usage: 827.0 MB

,y,x,spatial_ref,time,NDVI,geometry
0,259915.0,981475.0,2263,2021-07-24 15:49:11.024,0.438160,POINT (981475 259915)
1,259915.0,981485.0,2263,2021-07-24 15:49:11.024,0.263712,POINT (981485 259915)
2,259915.0,981495.0,2263,2021-07-24 15:49:11.024,0.263712,POINT (981495 259915)
3,259915.0,981505.0,2263,2021-07-24 15:49:11.024,0.263712,POINT (981505 259915)
4,259915.0,981515.0,2263,2021-07-24 15:49:11.024,0.700253,POINT (981515 259915)

In [6]:
gdf_lst.info()
gdf_lst.head()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 2191460 entries, 0 to 2191459
Data columns (total 2 columns):
 #   Column    Dtype
---  ------    -----
 0   LST       float64
 1   geometry  geometry
dtypes: float64(1), geometry(1)
memory usage: 33.4 MB

        LST               geometry
0  6.896887  POINT (981465 259905)
1  6.896887  POINT (981495 259905)
2  6.896887  POINT (981525 259905)
3  6.790928  POINT (981555 259905)
4  6.790928  POINT (981585 259905)

In [7]:
df_weather.info()
df_weather.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 338 entries, 0 to 337
Data columns (total 7 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Date / Time                  338 non-null    datetime64[ns]
 1   Air Temp at Surface [degC]   338 non-null    float64
 2   Relative Humidity [percent]  338 non-null    float64
 3   Avg Wind Speed [m/s]         338 non-null    float64
 4   Wind Direction [degrees]     338 non-null    int64
 5   Solar Flux [W/m^2]           338 non-null    int64
 6   location                     338 non-null    object
dtypes: datetime64[ns](1), float64(3), int64(2), object(1)
memory usage: 18.6+ KB

,Date / Time,Air Temp at Surface [degC],Relative Humidity [percent],Avg Wind Speed [m/s],Wind Direction [degrees],Solar Flux [W/m^2],location
0,2021-07-24 06:00:00,19.3,88.2,0.8,335,12,Bronx
1,2021-07-24 06:05:00,19.4,87.9,0.8,329,18,Bronx
2,2021-07-24 06:10:00,19.3,87.6,0.7,321,25,Bronx
3,2021-07-24 06:15:00,19.4,87.4,0.5,307,33,Bronx
4,2021-07-24 06:20:00,19.4,87.0,0.2,301,42,Bronx

## 2. Building footprints

***a. Buffer Creation:***

Create a circular buffer (e.g., 100 meters) around each UHI point. This defines the area we'll use to aggregate nearby building features.

***b. Spatial Join:***

Use a spatial join to determine which building footprints fall within each UHI point's buffer. Then, you can calculate summary statistics (count, mean height, total area, etc.) for those buildings.

In [8]:
# Create a 100-meter buffer around each UHI point
df_uhi['buffer'] = df_uhi.geometry.buffer(100)

# Perform a spatial join to find buildings that intersect with each buffer
joined = gpd.sjoin(gdf_buildings, df_uhi.set_geometry('buffer'), how='inner', predicate='intersects')

# Aggregate the building data by each UHI point (index_right)
agg_buildings = joined.groupby('index_right').agg(
    building_count=('heightroof', 'count'),
    mean_height=('heightroof', 'mean'),
    total_area=('calculated_area_sqm', 'sum')
).reset_index()

# Merge the aggregated building features back to the UHI dataframe
df_uhi = df_uhi.reset_index().merge(agg_buildings, left_index=True, right_on='index_right', how='left')

# Assuming a 100m buffer: area of buffer = π * (100^2) ≈ 31416 m²
buffer_area = 31416  # square meters
df_uhi['building_area_ratio'] = df_uhi['total_area'] / buffer_area

In [9]:
df_uhi.info()
df_uhi.head()

<class 'geopandas.geodataframe.GeoDataFrame'>
Index: 11229 entries, 0.0 to nan
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   index                11229 non-null  int64
 1   Longitude            11229 non-null  float64
 2   Latitude             11229 non-null  float64
 3   datetime             11229 non-null  datetime64[ns]
 4   UHI Index            11229 non-null  float64
 5   geometry             11229 non-null  geometry
 6   buffer               11229 non-null  geometry
 7   index_right          11229 non-null  int64
 8   building_count       10077 non-null  float64
 9   mean_height          10077 non-null  float64
 10  total_area           10077 non-null  float64
 11  building_area_ratio  10077 non-null  float64
dtypes: datetime64[ns](1), float64(7), geometry(2), int64(2)
memory usage: 1.1 MB

,index,Longitude,Latitude,datetime,UHI Index,geometry,buffer,index_right,building_count,mean_height,total_area,building_area_ratio
0.0,0,-73.909167,40.813107,2021-07-24 15:53:00,1.030289,POINT (1009393.606 235526.824),"POLYGON ((1009493.606 235526.824, 1009493.124 ...",0,1.0,65.100000,571.589876,0.018194
1.0,1,-73.909187,40.813045,2021-07-24 15:53:00,1.030289,POINT (1009388.093 235504.35),"POLYGON ((1009488.093 235504.35, 1009487.611 2...",1,2.0,61.070000,726.985385,0.023141
2.0,2,-73.909215,40.812978,2021-07-24 15:53:00,1.023798,POINT (1009380.276 235480.052),"POLYGON ((1009480.276 235480.052, 1009479.794 ...",2,3.0,50.450000,826.924125,0.026322
3.0,3,-73.909242,40.812908,2021-07-24 15:53:00,1.023798,POINT (1009372.92 235454.541),"POLYGON ((1009472.92 235454.541, 1009472.438 2...",3,5.0,70.714769,2776.139542,0.088367
4.0,4,-73.909257,40.812845,2021-07-24 15:53:00,1.021634,POINT (1009368.791 235431.463),"POLYGON ((1009468.791 235431.463, 1009468.31 2...",4,5.0,70.714769,2776.139542,0.088367

## 3. NDVI Aggregation

***a. Spatial Join***

Join the NDVI GeoDataFrame (which contains pixel-level NDVI values) with the UHI buffers (100m).

***b. Aggregation:***

Group by each UHI point (using the corresponding index from the UHI data) and compute the mean (and optionally other statistics) of NDVI values within that buffer.

***c. Merge back:***

Merge these aggregated NDVI features back into the UHI dataset.

In [10]:
# Spatial join: find NDVI pixels that intersect with each UHI point buffer.
joined_ndvi = gpd.sjoin(gdf_ndvi, df_uhi.set_geometry('buffer'),
                        how='inner', predicate='intersects')

# Aggregate NDVI values by UHI point (index_right)
agg_ndvi = joined_ndvi.groupby('index_right').agg(
    mean_ndvi=('NDVI', 'mean'),
    median_ndvi=('NDVI', 'median'),
    std_ndvi=('NDVI', 'std')
).reset_index()

# Merge aggregated NDVI features back to the UHI dataframe
df_uhi = df_uhi.reset_index().merge(agg_ndvi, left_index=True, right_on='index_right', how='left')

In [11]:
df_uhi.info()
df_uhi.head()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 11229 entries, 0 to 11228
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   index_right          11229 non-null  int64
 1   level_0              10077 non-null  float64
 2   index                11229 non-null  int64
 3   Longitude            11229 non-null  float64
 4   Latitude             11229 non-null  float64
 5   datetime             11229 non-null  datetime64[ns]
 6   UHI Index            11229 non-null  float64
 7   geometry             11229 non-null  geometry
 8   buffer               11229 non-null  geometry
 9   index_right_x        11229 non-null  int64
 10  building_count       10077 non-null  float64
 11  mean_height          10077 non-null  float64
 12  total_area           10077 non-null  float64
 13  building_area_ratio  10077 non-null  float64
 14  index_right_y        11229 non-null  int64
 15  mean_ndvi            11229 non-null  float64
 16  median_ndvi          11229 non-null  float64
 17  std_ndvi             11229 non-null  float64
dtypes: datetime64[ns](1), float64(11), geometry(2), int64(4)
memory usage: 1.5 MB

,index_right,level_0,index,Longitude,Latitude,datetime,UHI Index,geometry,buffer,index_right_x,building_count,mean_height,total_area,building_area_ratio,index_right_y,mean_ndvi,median_ndvi,std_ndvi
0,0,0.0,0,-73.909167,40.813107,2021-07-24 15:53:00,1.030289,POINT (1009393.606 235526.824),"POLYGON ((1009493.606 235526.824, 1009493.124 ...",0,1.0,65.100000,571.589876,0.018194,0,0.961880,0.311532,3.674295
1,1,1.0,1,-73.909187,40.813045,2021-07-24 15:53:00,1.030289,POINT (1009388.093 235504.35),"POLYGON ((1009488.093 235504.35, 1009487.611 2...",1,2.0,61.070000,726.985385,0.023141,1,0.507495,0.347632,1.900518
2,2,2.0,2,-73.909215,40.812978,2021-07-24 15:53:00,1.023798,POINT (1009380.276 235480.052),"POLYGON ((1009480.276 235480.052, 1009479.794 ...",2,3.0,50.450000,826.924125,0.026322,2,0.761768,0.425577,2.521862
3,3,3.0,3,-73.909242,40.812908,2021-07-24 15:53:00,1.023798,POINT (1009372.92 235454.541),"POLYGON ((1009472.92 235454.541, 1009472.438 2...",3,5.0,70.714769,2776.139542,0.088367,3,0.928148,0.425577,2.962296
4,4,4.0,4,-73.909257,40.812845,2021-07-24 15:53:00,1.021634,POINT (1009368.791 235431.463),"POLYGON ((1009468.791 235431.463, 1009468.31 2...",4,5.0,70.714769,2776.139542,0.088367,4,1.049445,0.413155,3.231100

## 4. LST Aggregation

***a. Spatial Join***

Join the LST GeoDataFrame with the UHI buffers.

***b. Aggregation:***

Group by UHI point and compute the mean, maximum, or other relevant statistics of the LST values.

***c. Merge back:***

Merge the aggregated LST data back into the UHI dataset.

In [12]:
df_uhi = df_uhi.drop(columns=['level_0', 'index_right_x', 'index_right_y'])
# Spatial join: find LST pixels that intersect with each UHI point buffer.
joined_lst = gpd.sjoin(gdf_lst, df_uhi.set_geometry('buffer'),
                       how='inner', predicate='intersects')

# Aggregate LST values by UHI point (index_right)
agg_lst = joined_lst.groupby('index_right').agg(
    mean_lst=('LST', 'mean'),
    max_lst=('LST', 'max')
).reset_index()

# Merge aggregated LST features back to the UHI dataframe
df_uhi = df_uhi.reset_index().merge(agg_lst, left_index=True, right_on='index_right', how='left')

In [13]:
df_uhi.info()
df_uhi.head()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 11229 entries, 0 to 11228
Data columns (total 20 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   index_right          11229 non-null  int64
 1   level_0              11229 non-null  int64
 2   index_right_x        11229 non-null  int64
 3   index                11229 non-null  int64
 4   Longitude            11229 non-null  float64
 5   Latitude             11229 non-null  float64
 6   datetime             11229 non-null  datetime64[ns]
 7   UHI Index            11229 non-null  float64
 8   geometry             11229 non-null  geometry
 9   buffer               11229 non-null  geometry
 10  building_count       10077 non-null  float64
 11  mean_height          10077 non-null  float64
 12  total_area           10077 non-null  float64
 13  building_area_ratio  10077 non-null  float64
 14  mean_ndvi            11229 non-null  float64
 15  median_ndvi          11229 non-null  float64
 16  std_ndvi             11229 non-null  float64
 17  index_right_y        11229 non-null  int64
 18  mean_lst             11229 non-null  float64
 19  max_lst              11229 non-null  float64
dtypes: datetime64[ns](1), float64(12), geometry(2), int64(5)
memory usage: 1.7 MB

,index_right,level_0,index_right_x,index,Longitude,Latitude,datetime,UHI Index,geometry,buffer,building_count,mean_height,total_area,building_area_ratio,mean_ndvi,median_ndvi,std_ndvi,index_right_y,mean_lst,max_lst
0,0,0,0,0,-73.909167,40.813107,2021-07-24 15:53:00,1.030289,POINT (1009393.606 235526.824),"POLYGON ((1009493.606 235526.824, 1009493.124 ...",1.0,65.100000,571.589876,0.018194,0.961880,0.311532,3.674295,0,38.926957,39.720133
1,1,1,1,1,-73.909187,40.813045,2021-07-24 15:53:00,1.030289,POINT (1009388.093 235504.35),"POLYGON ((1009488.093 235504.35, 1009487.611 2...",2.0,61.070000,726.985385,0.023141,0.507495,0.347632,1.900518,1,38.706348,39.720133
2,2,2,2,2,-73.909215,40.812978,2021-07-24 15:53:00,1.023798,POINT (1009380.276 235480.052),"POLYGON ((1009480.276 235480.052, 1009479.794 ...",3.0,50.450000,826.924125,0.026322,0.761768,0.425577,2.521862,2,38.498570,39.720133
3,3,3,3,3,-73.909242,40.812908,2021-07-24 15:53:00,1.023798,POINT (1009372.92 235454.541),"POLYGON ((1009472.92 235454.541, 1009472.438 2...",5.0,70.714769,2776.139542,0.088367,0.928148,0.425577,2.962296,3,38.253412,39.180086
4,4,4,4,4,-73.909257,40.812845,2021-07-24 15:53:00,1.021634,POINT (1009368.791 235431.463),"POLYGON ((1009468.791 235431.463, 1009468.31 2...",5.0,70.714769,2776.139542,0.088367,1.049445,0.413155,3.231100,4,38.077473,39.180086

## 5. Weather data Integration

***a. Temporal matching***

For each UHI point (which has a timestamp), select weather observations within a time window around that measurement (e.g., ±15 minutes).

***b. Aggregation:***

Compute summary statistics (mean, median) for weather variables within that time window.

***c. Merge back:***

Merge the aggregated LST data back into the UHI dataset.

In [14]:
# Convert weather 'Date / Time' to datetime if not already done
df_weather['Date / Time'] = pd.to_datetime(df_weather['Date / Time'], errors='coerce')

# Define a time window (e.g., ±15 minutes) for matching
time_window = pd.Timedelta('15 minutes')

def aggregate_weather(uhi_time):
    # Filter weather records close to the UHI timestamp
    weather_subset = df_weather[(df_weather['Date / Time'] >= uhi_time - time_window) &
                                (df_weather['Date / Time'] <= uhi_time + time_window)]
    if len(weather_subset) == 0:
        return pd.Series({
            'mean_air_temp': None,
            'mean_humidity': None,
            'mean_wind_speed': None,
            'mean_solar_flux': None
        })
    return pd.Series({
        'mean_air_temp': weather_subset['Air Temp at Surface [degC]'].mean(),
        'mean_humidity': weather_subset['Relative Humidity [percent]'].mean(),
        'mean_wind_speed': weather_subset['Avg Wind Speed [m/s]'].mean(),
        'mean_solar_flux': weather_subset['Solar Flux [W/m^2]'].mean()
    })

# Apply the aggregation function to each UHI point
weather_features = df_uhi['datetime'].apply(aggregate_weather)

# Merge the weather features into the UHI dataframe
df_uhi = pd.concat([df_uhi, weather_features], axis=1)

In [16]:
df_uhi.info()
df_uhi.head()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 11229 entries, 0 to 11228
Data columns (total 24 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   index_right          11229 non-null  int64
 1   level_0              11229 non-null  int64
 2   index_right_x        11229 non-null  int64
 3   index                11229 non-null  int64
 4   Longitude            11229 non-null  float64
 5   Latitude             11229 non-null  float64
 6   datetime             11229 non-null  datetime64[ns]
 7   UHI Index            11229 non-null  float64
 8   geometry             11229 non-null  geometry
 9   buffer               11229 non-null  geometry
 10  building_count       10077 non-null  float64
 11  mean_height          10077 non-null  float64
 12  total_area           10077 non-null  float64
 13  building_area_ratio  10077 non-null  float64
 14  mean_ndvi            11229 non-null  float64
 15  median_ndvi          11229 non-null  float64
 16  std_ndvi             11229 non-null  float64
 17  index_right_y        11229 non-null  int64
 18  mean_lst             11229 non-null  float64
 19  max_lst              11229 non-null  float64
 20  mean_air_temp        11229 non-null  float64
 21  mean_humidity        11229 non-null  float64
 22  mean_wind_speed      11229 non-null  float64
 23  mean_solar_flux      11229 non-null  float64
dtypes: datetime64[ns](1), float64(16), geometry(2), int64(5)
memory usage: 2.1 MB

,index_right,level_0,index_right_x,index,Longitude,Latitude,datetime,UHI Index,geometry,buffer,...,mean_ndvi,median_ndvi,std_ndvi,index_right_y,mean_lst,max_lst,mean_air_temp,mean_humidity,mean_wind_speed,mean_solar_flux
0,0,0,0,0,-73.909167,40.813107,2021-07-24 15:53:00,1.030289,POINT (1009393.606 235526.824),"POLYGON ((1009493.606 235526.824, 1009493.124 ...",...,0.961880,0.311532,3.674295,0,38.926957,39.720133,27.041667,47.1,3.058333,478.666667
1,1,1,1,1,-73.909187,40.813045,2021-07-24 15:53:00,1.030289,POINT (1009388.093 235504.35),"POLYGON ((1009488.093 235504.35, 1009487.611 2...",...,0.507495,0.347632,1.900518,1,38.706348,39.720133,27.041667,47.1,3.058333,478.666667
2,2,2,2,2,-73.909215,40.812978,2021-07-24 15:53:00,1.023798,POINT (1009380.276 235480.052),"POLYGON ((1009480.276 235480.052, 1009479.794 ...",...,0.761768,0.425577,2.521862,2,38.498570,39.720133,27.041667,47.1,3.058333,478.666667
3,3,3,3,3,-73.909242,40.812908,2021-07-24 15:53:00,1.023798,POINT (1009372.92 235454.541),"POLYGON ((1009472.92 235454.541, 1009472.438 2...",...,0.928148,0.425577,2.962296,3,38.253412,39.180086,27.041667,47.1,3.058333,478.666667
4,4,4,4,4,-73.909257,40.812845,2021-07-24 15:53:00,1.021634,POINT (1009368.791 235431.463),"POLYGON ((1009468.791 235431.463, 1009468.31 2...",...,1.049445,0.413155,3.231100,4,38.077473,39.180086,27.041667,47.1,3.058333,478.666667